#Galton's data
galton<-read.table("Galton.txt", header=TRUE)
col=("galton$Gender")
plot(galton$Height~galton$Parent.avg, col=c(1:2))
model_galton<-lm(galton$Height~galton$Parent.avg*galton$Gender)
hist(model_galton$residuals, breaks = 24)
qqnorm(model_galton$residuals)
qqline(model_galton$residuals)
plot(model_galton$residuals ~ model_galton$fitted.values)
boxplot(model_galton$residuals ~ galton$Gender)
anova(model_galton)
summary(model_galton)




mouse <- read.table("mouse.txt", header = T)
boxplot(mouse$LitterMass ~ mouse$FUR * mouse$Day, col = (3:4))
model <- lm(mouse$LitterMass ~ mouse$FUR)
hist(model$residuals, breaks = 24)
qqnorm(model$residuals)
qqline(model$residuals)
plot(model$residuals ~ model$fitted.values)
boxplot(model$residuals ~ mouse$FUR)
anova(model)
boxplot(mouse$LitterMass ~ mouse$FUR)

shaved <- subset(mouse, mouse$FUR == "shave")
unshaved <- subset(mouse, mouse$FUR == "non-shave")

model1 <- lm(shaved$LitterMass  ~ shaved$Day)
hist(model1$residuals, breaks = 24)
qqnorm(model1$residuals)
qqline(model1$residuals)
plot(model1$residuals ~ model1$fitted.values)
plot(cooks.distance(model1) ~ hatvalues(model1))
summary(model1)

model2 <- lm(unshaved$LitterMass  ~ unshaved$Day)
hist(model2$residuals, breaks = 24)
qqnorm(model2$residuals)
qqline(model2$residuals)
plot(model2$residuals ~ model2$fitted.values)
plot(cooks.distance(model2) ~ hatvalues(model2))
summary(model2)

model3 <- lm(mouse$LitterMass ~ mouse$FUR + mouse$Day)
hist(model3$residuals, breaks = 24)
qqnorm(model3$residuals)
qqline(model3$residuals)
plot(model3$residuals ~ model3$fitted.values)
plot(cooks.distance(model3) ~ hatvalues(model3))
anova(model3)
summary(model3)

model4 <- lm(mouse$LitterMass ~ mouse$FUR * mouse$Day)
hist(model4$residuals, breaks = 24)
qqnorm(model4$residuals)
qqline(model4$residuals)
plot(model4$residuals ~ model4$fitted.values)
plot(cooks.distance(model4) ~ hatvalues(model4))
anova(model4)
summary(model4)

eggs <- read.table("FinchEggs.txt", header = T)
model5 <- lm(eggs$Egg_mass ~ eggs$F_mass * eggs$Mating_System)
hist(model5$residuals, breaks = 24)
qqnorm(model5$residuals)
qqline(model5$residuals)
plot(model5$residuals ~ model5$fitted.values)
plot(cooks.distance(model5) ~ hatvalues(model5))
anova(model5)
summary(model5)
plot(eggs$Egg_mass ~ eggs$F_mass, col = (4:6)[factor(eggs$Mating_System)], pch = 16)
