grades<-read.table("quizzes1_2.txt", header=TRUE)
str(grades)
hist(grades$Q2, breaks=22, xlab="Quiz 2 grades", main=NULL)
summary(grades$Q2)
summary(grades$Q1)
hist(grades$Q1, breaks=22, xlab="Quiz 1 grades", main=NULL)
plot(grades$Q2~grades$Q1)
model<-lm(grades$Q2~grades$Q1)
summary(model)
boxplot(grades$Q2, grades$Q1)
