Suzi<-read.table("Suzidata.txt", header=TRUE)
str(Suzi)
col=("Suzi$HerbivoreSpecies")
Suzi$HerbivoreSpecies<-as.factor(Suzi$HerbivoreSpecies)
plot(Suzi$Silica~Suzi$HerbivoreDamage, col=c(1:3), pch=16)
hist(Suzi$Silica)
boxplot(Suzi$Silica~Suzi$HerbivoreSpecies, col=c(1:3))
model<-lm(Suzi$Silica~Suzi$HerbivoreDamage*Suzi$HerbivoreSpecies)
summary(model)
anova(model)
model2<-lm(Suzi$Silica~Suzi$HerbivoreDamage+Suzi$HerbivoreSpecies)
anova(model2)
summary(model2)
hist(model2$residuals, breaks = 20)
qqnorm(model2$residuals)
qqline(model2$residuals)
library(car)
qqPlot(model2$residuals)
col=(Suzi$HerbivoreSpecies)
plot(model2$residuals ~ model2$fitted.values, col=c(1:3), pch=16)
abline(5,0)
abline(0,0)
abline(-5,0)
sheep_res<-subset(model2$residuals,Suzi$HerbivoreSpecies=="1.Sheep")
vole_res<-subset(model2$residuals,Suzi$HerbivoreSpecies=="2.Vole")
reddeer_res<subset(model2$residuals,Suzi$HerbivoreSpecies=="3.RedDeer")
rd_res<-subset(model2$residuals,Suzi$HerbivoreSpecies=="3.RedDeer")
hist(sheep_res)
hist(vole_res)
hist(rd_res)
qqnorm(sheep_res)
qqline(sheep_res)
qqnorm(vole_res)
qqline(vole_res)
qqnorm(rd_res)
qqline(rd_res)
boxplot(sheep_res, vole_res, rd_res, col=c(1:3))
plot(cooks.distance(model2) ~ hatvalues(model2))
anova(model2)
summary(model2)
Suzi2<-read.table("Suzidata.txt", header=TRUE)
Suzi2$HerbivoreSpecies=NULL
pairs(Suzi2[,4:1])



penguins<-read.table("penguins.txt", header=TRUE)
head(penguins)
str(penguins)
boxplot(penguins$bill_length_mm~penguins$species)
col=(penguins$species)
plot(penguins$bill_length_mm~penguins$bill_depth_mm, col=c(1:3), pch=16)
col=(penguins$year)
plot(penguins$bill_length_mm~penguins$bill_depth_mm, col=c(4:6), pch=16)
model_penguins<-lm(penguins$bill_length_mm~penguins$bill_depth_mm+penguins$species+penguins$sex+penguins$year)
anova(model_penguins)
summary(model_penguins)

model_penguins2<-lm(penguins$flipper_length_mm~penguins$year*penguins$species)
anova(model_penguins2)
summary(model_penguins2)
model3_penguins2<-lm(penguins$bill_length_mm~penguins$year*penguins$sex)
anova(model3_penguins2)
summary(model3_penguins2)


model_penguins3<-lm(penguins$bill_depth_mm~penguins$species*penguins$sex)
anova(model_penguins3)
summary(model_penguins3)
model3_penguins2<-lm(penguins$bill_length_mm~penguins$year*penguins$sex)
anova(model3_penguins2)
summary(model3_penguins2)





boxplot(penguins$bill_length_mm~penguins$species)
col=(penguins$species)
plot(penguins$bill_length_mm~penguins$bill_depth_mm, col=(1:3), pch=16)
hist(model_penguins$residuals, breaks = 20)
qqnorm(model_penguins$residuals)
qqline(model_penguins$residuals)
col=(penguins$species)
plot(model_penguins$residuals ~ model_penguins$fitted.values, col=c(1:3), pch=16)
abline(5,0)
abline(0,0)
abline(-5,0)
plot(cooks.distance(model_penguins) ~ hatvalues(model_penguins))

pairs(penguins[, 7:4])
Gentoo<-subset(penguins, penguins$species=="Gentoo")
pairs(Gentoo[, 7:4])

model_Gentoo<-lm(Gentoo$body_mass_g~(Gentoo$bill_length_mm+Gentoo$bill_depth_mm+Gentoo$flipper_length_mm+Gentoo$bill_depth_mm*Gentoo$flipper_length_mm))
anova(model_Gentoo)
summary(model_Gentoo)
hist(model_Gentoo$residuals, breaks = 20)
qqnorm(model_Gentoo$residuals)
qqline(model_Gentoo$residuals)
plot(model_Gentoo$residuals ~ model_Gentoo$fitted.values, pch=16)
abline(5,0)
abline(0,0)
abline(-5,0)
plot(cooks.distance(model_Gentoo) ~ hatvalues(model_Gentoo))




whales<-read.table("whaledata0.txt", header=TRUE)
head(whales)
hist(whales$number.whales)
whales$ln.number.whales<-log(whales$number.whales)
plot(whales$ln.number.whales~whales$depth)
plot(whales$number.whales~whales$gradient)
plot(whales$number.whales~whales$latitude)
plot(whales$number.whales~whales$longitude)
boxplot(whales$ln.number.whales~whales$water.noise)
pairs(whales[,4:8])
model_whales<-lm(whales$ln.number.whales~whales$water.noise)
anova(model_whales)
summary(model_whales)
hist(model_whales$residuals, breaks = 20)
qqnorm(model_whales$residuals)
qqline(model_whales$residuals)
col=(whales$water.noise)
plot(model_whales$residuals ~ model_whales$fitted.values, col=c(1:3), pch=16)
abline(5,0)
abline(0,0)
abline(-5,0)
plot(cooks.distance(model_whales) ~ hatvalues(model_whales))

rice<-read.table("RiceSDW.txt", header=TRUE)
head(rice)
boxplot(rice$SDW~rice$Treatment.ID)
rice$ln.SDW<-log(rice$SDW)
boxplot(rice$ln.SDW~rice$Treatment.ID)
model_rice<-lm(rice$ln.SDW~rice$Treatment.ID+rice$Variety)
anova(model_rice)
summary(model_rice)
plot(model_rice$residuals~model_rice$fitted.values)


fruit_root<-read.table("fruitrootdata.txt", header=TRUE)
head(fruit_root)
ozone<-read.table("ozone_pollution.txt", header=TRUE)
head(ozone)
plot(ozone$ozone~ozone$rad)
plot(ozone$ozone~ozone$temp)
plot(ozone$ozone~ozone$wind)
pairs(ozone[,4:1])
model_ozone<-lm(ozone$ozone~(ozone$rad+ozone$temp+ozone$wind)^2)
anova(model_ozone)
summary(model_ozone)
model_ozone2<-lm(ozone$ozone~ozone$rad+ozone$temp+ozone$wind)
anova(model_ozone2)
summary(model_ozone2)

gain<-read.table("Gain.txt", header=TRUE)
head(gain)

AGR<-read.table("phosriverCO2AGR.txt", header=TRUE)
head(AGR)
model1<-lm(AGR$AGR~AGR$CO2)
model2<-lm(AGR$AGR~AGR$CO2+AGR$River)
model3<-lm(AGR$AGR~AGR$CO2*AGR$River)
anova(model1)
anova(model2)
anova(model3)
col=("AGR$River")
pch=("AGR$River")
plot(AGR$AGR~AGR$CO2, col=(1:3), pch=(16:18), cex=2, xlab="CO2 level", ylab="algal growth rate")

anova(model2)
summary(model2)
