#quiz one
mussels<-read.table("mussel_length.txt", header=TRUE)
str(mussels)
mean(mussels$length~mussels$temperature)
mussels_5D<-subset(mussels, temperature=="LEN5D")
rm(meanLEN5D)
mussels_15D<-subset(mussels, temperature=="LEN15D")
mean_5D<-mean(mussels_5D$length)
sd_5D<-sd(mussels_5D$length)
mean_15D<-mean(mussels_15D$length)
sd_15D<-sd(mussels_15D$length)
Q_5D<-quantile(mussels_5D$length, probs = c(0.25, 0.75))
Q_15D<-quantile(mussels_15D$length, probs = c(0.25, 0.75))
Q_90_5D<-quantile(mussels_5D$length, probs = c(0.5, 0.89, 0.90))
Q_10_15D<-quantile(mussels_15D$length, probs = c(0.1))
prob_185_5D<-1-pnorm(185,mean(mussels_5D$length),sd(mussels_5D$length)) 
prob_185_15D<-pnorm(185,mean(mussels_15D$length),sd(mussels_15D$length)) 
t.test(mussels$length ~ mussels$temperature, var.equal = TRUE)
18.39/19.79
t.test(mussels$length ~ mussels$temperature, var.equal = FALSE)

grades<-read.table("grades.txt", header=TRUE)
lapply(grades$CA1Quiz,as.numeric)
str(grades)
head(grades)
hist(grades$CA1Quiz, breaks=22,xlim=c(0,22), xlab="CGS grade Quiz One", main=NULL)
